matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      addons: &gcc7
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
    - os: linux
      dist: trusty
      compiler: clang
      addons: *gcc7
    - os: linux
      dist: xenial
      compiler: gcc
      addons: *gcc7
    - os: linux
      dist: xenial
      compiler: clang
      addons: *gcc7
    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang
    - os: osx
      osx_image: xcode10
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode11
sudo: false
language: cpp
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC"  == "gcc" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 10; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 10; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CC"  == "gcc" ]]; then sudo update-alternatives --set gcc /usr/bin/gcc-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$CXX" == "g++" ]]; then sudo update-alternatives --set g++ /usr/bin/g++-7; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then HOMEBREW_NO_AUTO_UPDATE=1 HOMEBREW_NO_INSTALL_CLEANUP=1 brew install re2c ; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then choco install re2c python ; fi
script:
  - ./misc/ci.py
  - python3 configure.py --bootstrap
  - ./ninja all
  - ./ninja_test --gtest_filter=-SubprocessTest.SetWithLots
  - ./misc/ninja_syntax_test.py
  - ./misc/output_test.py
